In [1]:
!pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl 
!pip install torchvision 

ERROR: torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.


In [2]:
import torch

In [3]:
import torch    # Similar to numpy Library
import torch.autograd as autograd  # Tape based automatic diffrentiation library
import torch.nn as nn    # Imp library to work on NN
import torch.optim as optim  # Torch optimization Library

torch.manual_seed(123)

# Creating Tensor

In [4]:
# Create a torch.Tensor object from python list
v = [1, 2, 3]
print(type(v))
v_tensor = torch.Tensor(v)
print(v_tensor)

# Create a torch.Tensor object of size 2x3 from 2x3 matrix
m2x3 = [[1, 2, 3], [4, 5, 6]]
m2x3_tensor = torch.Tensor(m2x3)
print(m2x3_tensor)

# Create a 3D torch.Tensor object of size 3x3x3.
m3x3x3 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[10, 11, 12],[13, 14, 15], [16, 17, 18]],
            [[19, 20, 21],[22, 23, 24], [25, 26, 27]]]
m3x3x3_tensor = torch.Tensor(m3x3x3)
print(m3x3x3_tensor)

#Create a 4Dtensor from random data and given dimensions (in this case 3x4x5x6) with torch.randn()
m4x3x3x3_tensor = torch.randn((4, 3, 3, 3))
m4x3x3x3_tensor.shape
print(m4x3x3x3_tensor)

<class 'list'>
tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])
tensor([[[[ 3.3737e-01, -1.7778e-01, -3.0353e-01],
          [-5.8801e-01,  3.4861e-01,  6.6034e-01],
          [-2.1964e-01, -3.7917e-01,  7.6711e-01]],

         [[-1.1925e+00,  6.9835e-01, -1.4097e+00],
          [ 1.7938e-01,  1.8951e+00,  4.9545e-01],
          [ 2.6920e-01, -7.7020e-02, -1.0205e+00]],

         [[-1.6896e-01,  9.1776e-01,  1.5810e+00],
          [ 1.3010e+00,  1.2753e+00, -2.0095e-01],
          [ 4.9647e-01, -1.5723e+00,  9.6657e-01]]],


        [[[-1.1481e+00, -1.1589e+00,  3.2547e-01],
          [-6.3151e-01, -2.8400e+00, -1.3250e+00],
          [ 1.7843e-01, -2.1338e+00,  1.0524e+00]],

         [[-3.8848e-01, -9.3435e-01, -4.9914e-01],
      

## What is a multidimensional tensor?
Since we frequently deal with n > 3 dimensional tensors, its understanding is very important. The best way to think of a higher (n) dimensional object (and tensor in particular) is as of a container which keeps a series of n-1 dimensional objects "inside" of it. We can "pull out" these "inner" objects by indexing in to higher dimensional tensor container. Let's have a look on some examples:

For a vector v (dim(v)=1), indexing into it ("pulling out of it") returns its "slice" - a scalar s (dim(s)=0).

For a matrix, indexing into it returns its "slice" - a (row or column) vector.

3D tensor can be seen as a cube or 3D rectangular consisting of horizontally "stacked" matrices. So if we index into a such tensor it will give us its slice which is a matrix!

We can't easily visualize 5D (or n-D) tensors, but the idea is actually the same. If we index in to them, we will pull out an object of dimension n-1.

E.g. a 4D tensor can be seen as a list of cubes or 3D reactangulars. If we index in to a 4D tensor, we will get 3D rectangulars.

IMG_0120.png

In [5]:
# Index into v_tensor and get a scalar
print(v_tensor[0])

# Index into m2x3_tensor and get a vector
print(m2x3_tensor[0])

# Index into m3x3x3_tensor and get a matrix
print(m3x3x3_tensor[0])

# Index into m4x3x3x3_tensor and get a 3D rectangular of size 4x5x6
print(m4x3x3x3_tensor[0])

tensor(1.)
tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[[ 0.3374, -0.1778, -0.3035],
         [-0.5880,  0.3486,  0.6603],
         [-0.2196, -0.3792,  0.7671]],

        [[-1.1925,  0.6984, -1.4097],
         [ 0.1794,  1.8951,  0.4954],
         [ 0.2692, -0.0770, -1.0205]],

        [[-0.1690,  0.9178,  1.5810],
         [ 1.3010,  1.2753, -0.2010],
         [ 0.4965, -1.5723,  0.9666]]])


## Operations with Tensors
You can operate on tensors in the ways you would expect. See the documentation http://pytorch.org/docs/torch.html for a complete list of operations.

Simple mathematical operations: Addition, Multiplication

In [6]:
x = torch.Tensor([1, 2, 3])
y = torch.Tensor([4, 5, 6])
print(x)
print(y)

w = torch.matmul(x, y)    # matmul is a scaler multiplication
print(w)

tensor([1., 2., 3.])
tensor([4., 5., 6.])
tensor(32.)


In [7]:
# By default, it concatenates along the axis with 0 (rows). It's "stacking" the rows.

x_1 = torch.randn(2, 5)
print(x_1)
y_1 = torch.randn(3, 5)
print(y_1)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 5)
print(x_2)
y_2 = torch.randn(2, 5)
print(y_2)
# second arg specifies which axis to concat along. Here we select 1 (columns). It's attaching the columns.
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
torch.cat([x_1, x_2])

tensor([[ 0.5485, -1.6063,  0.7281,  0.6609,  0.2391],
        [ 0.0340,  0.1164, -0.9905,  0.5646,  0.0686]])
tensor([[-1.0035, -0.7874,  0.9840,  0.2045, -0.3604],
        [ 1.2101, -1.0814,  0.0789,  0.2913, -0.5023],
        [-0.9306,  0.9086, -0.7788, -1.4453,  0.7636]])
tensor([[ 0.5485, -1.6063,  0.7281,  0.6609,  0.2391],
        [ 0.0340,  0.1164, -0.9905,  0.5646,  0.0686],
        [-1.0035, -0.7874,  0.9840,  0.2045, -0.3604],
        [ 1.2101, -1.0814,  0.0789,  0.2913, -0.5023],
        [-0.9306,  0.9086, -0.7788, -1.4453,  0.7636]])
tensor([[-0.2469,  0.5857,  0.9906,  0.0417, -1.1668],
        [ 1.3251, -0.7990,  0.6292, -1.2097, -2.1362]])
tensor([[-0.1212, -0.1443,  0.9969,  0.5697, -0.4930],
        [ 0.3155, -0.2275, -1.7942,  1.0417, -0.2358]])
tensor([[-0.2469,  0.5857,  0.9906,  0.0417, -1.1668, -0.1212, -0.1443,  0.9969,
          0.5697, -0.4930],
        [ 1.3251, -0.7990,  0.6292, -1.2097, -2.1362,  0.3155, -0.2275, -1.7942,
          1.0417, -0.2358]])


tensor([[ 0.5485, -1.6063,  0.7281,  0.6609,  0.2391],
        [ 0.0340,  0.1164, -0.9905,  0.5646,  0.0686],
        [-0.2469,  0.5857,  0.9906,  0.0417, -1.1668],
        [ 1.3251, -0.7990,  0.6292, -1.2097, -2.1362]])

### Remarl: If enter wrong value in row 11 or 13, we will get wrong solution for row 16

In [8]:
# By default, it concatenates along the axis with 0 (rows). It's "stacking" the rows.

x_1 = torch.randn(2, 5)
print(x_1)
y_1 = torch.randn(3, 5)
print(y_1)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
print(x_2)
y_2 = torch.randn(3, 5)
print(y_2)
# second arg specifies which axis to concat along. Here we select 1 (columns). It's attaching the columns.
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
torch.cat([x_1, x_2])

tensor([[-0.3030,  0.4934, -0.2766,  0.2439, -1.2116],
        [-0.1520,  0.1509, -0.6251, -0.4416,  0.3208]])
tensor([[-0.3273, -0.5305, -0.0172,  0.4719,  0.5671],
        [ 2.7930,  0.3229,  0.8552,  0.7492, -1.7119],
        [ 0.6025, -0.7018, -1.3130,  0.1574,  2.0114]])
tensor([[-0.3030,  0.4934, -0.2766,  0.2439, -1.2116],
        [-0.1520,  0.1509, -0.6251, -0.4416,  0.3208],
        [-0.3273, -0.5305, -0.0172,  0.4719,  0.5671],
        [ 2.7930,  0.3229,  0.8552,  0.7492, -1.7119],
        [ 0.6025, -0.7018, -1.3130,  0.1574,  2.0114]])
tensor([[ 0.1004,  0.8222, -0.0176],
        [ 1.2481, -0.0710,  2.1627]])
tensor([[ 1.5215, -1.0547,  1.7822,  1.9736, -0.3101],
        [-0.8211,  0.1315, -0.6948, -0.5823,  1.0035],
        [-1.4613,  0.8985,  0.6210, -0.9679,  0.6740]])


RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

## Reshaping Tensors
We can use the .view() method to reshape a tensor. Often we will need to reshape our data before passing it to a neuronal network.

Let's assume we have 64000 RGB images with the size of 28x28 pixels. We can define an array fo shape (64000, 3, 28, 28) to hold them, where 3 is number of color channels:

In [ ]:
x = torch.randn(64000, 3, 28, 28)
# Now we want to add a batch dimension of size 32. We can then infer the second dimension by placing -1:
x_rehsaped = x.view(32, -1, 3, 28, 28)
print(x_rehsaped.shape)

# Computation Graphs and Automatic Differentiation
A computation graph is a specification of what parameters with which operations are involved in the computation to give the output.

The fundamental class of Pytorch autograd.Variable keeps track of how it was created.

In [ ]:
# Variables wrap tensor objects
x = autograd.Variable(torch.Tensor([1, 2, 3]), requires_grad=True)
# You can access the data with the .data attribute
print(x.data)

y = autograd.Variable(torch.Tensor([4, 5, 6]), requires_grad=True)

# With autograd.Variable you can also perform all the same operations you did with tensors
z = x + y
print(z.data)

#  w knows also that it's result of addition of z lements (AddBackward)
operation = z.grad_fn
print(operation)

In [ ]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

## Gradient
    So now, what is the derivative of this sum with respect to the first component of x? Remember, that x is a tensor of 3 elements: $x = (x_0, x_1, x_2)$

    In math, we want a partial derivative of $s$ with respect to $x_0$: $\frac{\partial s}{\partial x_0}$

    Well, $s$ knows that it was created as a $sum$ of the tensor $z$ elements $(z_0, z_1, z_2)$. $z$ knows that it was the sum $x + y$. So

 
 
 
 
    And so $s$ contains enough information to determine that the derivative of $s$ with respect to $x_0$ is 1!

    Reminder: If you compute the partial derivative with respekt to one variable, you handle all other variables as constants. Therefore they all $(x_1, x_2, y_0, y_1, y_2)$ get zeroes, and the derivative of $f(x_0) = x_0$ is 1.

    First we need to run backpropagation and calculate gradients with respect to every variable. Note: if you run backward multiple times, the gradient will increment. That is because Pytorch accumulates the gradient into the .grad property, since for many models this is very convenient. Lets now have Pytorch compute the gradient, and see that we were right with our guess of 1:

In [ ]:
# calling .backward() on any variable will run backprop, starting from it.
s.backward(retain_graph=True)


In [ ]:
print(x)
print(x.grad)
print(y.grad)

### How NOT to break the computational graph
Let's create two torch tensors and add them up:

In [ ]:
x = torch.randn((2, 2))
y = torch.randn((2, 2))
z = x + y  # These are Tensor types, and backprop would not be possible

print(z)

In [ ]:
var_x = autograd.Variable(x, requires_grad=True)
var_y = autograd.Variable(y, requires_grad=True)
# var_z contains enough information to compute gradients, as we saw above
var_z = var_x + var_y
print(var_z.grad_fn)

In [ ]:
var_z_data = var_z.data
new_var_z = autograd.Variable(var_z_data)
print(new_var_z.grad_fn)

In [ ]:
new_var_z.backward(retain_graph=True)

# Cuda
Check wether GPU accelaration with CUDA is available

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    # creates a LongTensor and transfers it
    # to GPU as torch.cuda.LongTensor
    a = torch.LongTensor(10).fill_(3).cuda()
    print(type(a))
    b = a.cpu()
    # transfers it to CPU, back to
    # being a torch.LongTensor

# Create Linear Model using PyTorch

In [ ]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

In [ ]:
x = [i for i in range(20)] #list comprehention
x_train = np.array(x, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
print(x)
print(x_train.shape)

y = [(5*i + 2) for i in x] #list comprehention
y_train = np.array(y, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
print(y)
print(y_train.shape)

# Create Model Class

In [ ]:
class LinearRegressor(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressor, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)  
    
    def forward(self, x):
        out = self.linear(x)
        return out

input_dim = 1
output_dim = 1

model = LinearRegressor(input_dim, output_dim)

model

# Loss & Optimizer

In [ ]:
loss_function = nn.MSELoss()


optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
print(optimizer)
print(loss_function)

In [ ]:
epochs = 500

for epoch in range(epochs):
    epoch += 1
    #Convert inputs and outputs to torch variable
    inputs = Variable(torch.from_numpy(x_train))
    
    real_outputs = Variable(torch.from_numpy(y_train))
    
    # Reset Gradients
    optimizer.zero_grad()
    
    # Forward - compute the output
    pred_outputs = model(inputs)
    
    # Loss
    loss = loss_function(pred_outputs, real_outputs)
    
    # Backword - compute gradients
    loss.backward()
    
    # Update parameters
    optimizer.step()
    
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))
    #print('epoch {}, loss {} '. format(epoch, loss.data[0]))

In [ ]:
epochs = 500

for epoch in range(epochs):
    epoch += 1
    #Convert inputs and outputs to torch variable
    inputs = Variable(torch.from_numpy(x_train))
    
    real_outputs = Variable(torch.from_numpy(y_train))
    
    # Reset Gradients
    optimizer.zero_grad()
    
    # Forward - compute the output
    pred_outputs = model(inputs)
    
    # Loss
    loss = loss_function(pred_outputs, real_outputs)
    
    # Backword - compute gradients
    loss.backward()
    
    # Update parameters
    optimizer.step()
    
    print('epoch {}, loss {}'.format(epoch, loss.data[0]))